wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1672913685.559054
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.8.9
      5: 0.13.7
      8:
      - 4
      - 5
epochs:
  desc: null
  value: 100
